config/routes.rb
Rails.application.routes.draw do
  get 'message/create'
  devise_for :users
  root 'pages#home'
  get 'users/dashboard'
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to:'users#payment', as: 'settings_payment'
  get '/settings/payout', to:'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'


  post 'users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post'/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

   mount ActionCable.server => '/cable'

  resources :gigs do 
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end
  resources :requests
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :gigs
  has_many :requests
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :order
  has_one_attached :attachment_file
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  def last_message
    message = Message.where(conversation_id: self.id).last
    if message.present?
      return message
    else
      return Message.new updated_at: Time.now
    end
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :pricings
  has_many :orders
  has_many :reviews
  has_many_attached :photos
  has_rich_text :description

  accepts_nested_attributes_for :pricings

  validates :title, presence: {message: 'cannot be blank'}

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)

  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :request
  belongs_to :user
  enum status: [:pending, :accepted, :rejected]
  validates :amount, :days, numericality: { only_integer: true, message: "must be a numner"}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :gig, required: false
  belongs_to :requests, required: false
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  has_many :reviews

  enum status: [:inprogress, :completed]
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  belongs_to :gig
  enum pricing_type: [:basic, :standard, :premium]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :attachment_file
  has_many :offers, dependent: :delete_all
  has_many :orders

  validates :title, presence: {message: "cannot be empty"}
  validates :description, presence: {message: "cannot be empty"}
  validates :delivery, numericality: {only_integer: true, message:  "must be a number"}


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  belongs_to :gig, required: false
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  enum status: [:pending, :success]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User", optional: true
  belongs_to :gig, optional: true
  belongs_to :request, optional: true

  enum status: [:approved, :pending, :rejected]
  enum transaction_type: [:trans, :withdraw]
  enum source_type: [:system, :stripe]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 
         # :omniauthable

         validates :full_name, presence: true, length: {maximum: 50}

         has_one_attached :avatar

        has_many :gigs
        has_many :requests
         has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
        has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"
        has_many :offers


#   def self.from_omniauth(auth)
#     user = User.where(email: auth.info.email).first

#     if user
#       return user
#     else
#   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#     user.email = auth.info.email
#     user.password = Devise.friendly_token[0, 20]
#     user.full_name = auth.info.name   # assuming the user model has a name
#     user.image = auth.info.image # assuming the user model has an image
  

#     user.uid = auth.uid
#     user.provider = auth.provider
#    end
#   end
# end

end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/dashboard/index.html.erb
<div class="main-content-area">
  <div class="main-content-container">
    <div class="main-content">
      <div class="row">


        <div class="col-md-3 bg-primary">
          <div class="card text-white text-center">
            <h1><%= @user_count %></h1>
            <p>Users</p>
          </div>
        </div>

         <div class="col-md-3 bg-success">
          <div class="card text-white text-center">
            <h1><%= @gig_count %></h1>
            <p>Gig</p>
          </div>
        </div>
        

         <div class="col-md-3 bg-warning">
          <div class="card text-white text-center">
            <h1><%= @order_count %></h1>
            <p>Orders</p>
          </div>
        </div>
        

         <div class="col-md-3 bg-danger">
          <div class="card text-white text-center">
            <h1><%= @categories_count %></h1>
            <p>Categories</p>
          </div>
        </div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freelance</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://js.stripe.com/v3/"></script>


  <% if content_for?(:head)  %>
  <%= yield(:head) %>
  <% end %>
</head>

<body>
  <%= render 'shared/navbar' %>

  <%= render "shared/alert" %>



  <%= yield %>

 
</body>
</html>

app/views/pages/calendar.html.erb
<section class="section">
    <div class="container m-t-20">
        <div id="calendar"></div>
    </div>
</section>

<script>

    orders = <%= raw @orders.to_json %>

    function showOrders(orders) {
        return orders.map(function(o) {
            let code = '#ffdd57';

            if (new Date(o.due_date) < new Date()) {
                code = '#ff3860';
            } else if (new Date(o.due_date) > new Date(new Date().getTime() + (2*24*60*60*1000))) {
                code = '#23d160';
            }

            return {
                id: o.id,
                title: o.buyer_name,
                start: o.due_date,
                end: o.due_date,
                backgroundColor: code
            }
        })
    }

    var getQueryParam = function(param) {
        var found,
            item = window.location.search.substr(1).split("=");
        if (param == item[0]) {
            found = item[1]
        }
        return found;
    }

    $(function() {
        var start_date = getQueryParam('start_date') ? new Date(getQueryParam('start_date')) : new Date()
        var calendarEl = document.getElementById('calendar');
        var calendar = new Calendar(calendarEl, {
            header: {
                left: 'prev,next',
                right: 'dayGridMonth,listMonth'
            },
            defaultDate: start_date,
            plugins: [DayGridPlugin, ListPlugin],
            events: showOrders(orders),
            eventClick: function(info) {
                window.location.href = "/orders/" + info.event.id
            },
            defaultView: 'dayGridMonth'
        });

        calendar.render();

        $('.fc-prev-button').on('click', function() {
            window.location.search = 'start_date=' + calendar.state.currentDate.toISOString().split("T")[0]
        });

        $('.fc-next-button').on('click', function() {
            window.location.search = 'start_date=' + calendar.state.currentDate.toISOString().split("T")[0]
        });
    })
</script>

app/views/pages/home.html.erb
<% content_for :head do %>
<meta name="turbolinks-cache-control" content="no-cache">
<% end %>



<section class="hero is-medium has-bg-img">
  <div class="hero-body">

    <div class="container">
      <h1 class="title has-text-white">
        Encuentra Freelancers
<br>
Para Redes Sociales
</h1>
 <%= form_tag search_path, method: :get, class: "field has-addons" do %>
  <div class="control has-icons-left">
    <span class="icon is-small is-left">
    <i class="fa fa-search"></i>
  </span>
  <%= text_field_tag 'q', '', class: "input", placeholder: "" %>
</div>
<div class="control">
  <button class="
  button is-warning " type="submit">Buscar</button>
</div>

<% end %>
</div>

</div>
</section>



<section class="m-t-100">
  <div class="container">
  <h1 class="title is-4 p-l-10">Colaboraciones Populares</h1>
  <div id="carousel-category" class="hero-carousel">


    <div class="carousel-item">
      <div class="p-10">
        <%= link_to search_path(category: 11) do %>
        <div class="card-image">
          <%= image_tag "home/category_1.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white">Instagram</span><br />
            <span class="title is-4 has-text-white">Colaboraciones en Instagram</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>

     <div class="carousel-item">
      <div class="p-10">
          <%= link_to search_path(category: 2) do %>
        <div class="card-image">
          <%= image_tag "home/category_2.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white">Learn Your Business</span><br>
            <span class="title is-4 has-text-white">Data Entry</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>

      <div class="carousel-item">
      <div class="p-10">
          <%= link_to search_path(category: 3) do %>
        <div class="card-image">
          <%= image_tag "home/category_3.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white"> Build Your Brand</span><br>
            <span class="title is-4 has-text-white">Wordpress</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>

     <div class="carousel-item">
      <div class="p-10">
      <%= link_to search_path(category: 4) do %>
        <div class="card-image">
          <%= image_tag "home/category_4.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white">Color Your Dream</span><br>
            <span class="title is-4 has-text-white">Illustration</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>

      <div class="carousel-item">
      <div class="p-10">
      <%= link_to search_path(category: 5) do %>
        <div class="card-image">
          <%= image_tag "home/category_5.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white">Reach More Customers</span><br />
            <span class="title is-4 has-text-white">Social Media</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>

     <div class="carousel-item">
      <div class="p-10">
         <%= link_to search_path(category: 6) do %>
        <div class="card-image">
          <%= image_tag "home/category_6.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white">Branding</span><br>
            <span class="title is-4 has-text-white">Graphics Design</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>

     <div class="carousel-item">
      <div class="p-10">
        <%= link_to search_path(category: 7) do %>
        <div class="card-image">
          <%= image_tag "home/category_7.jpg", class: "is-background", width: "100%", height: "100%" %>
          <div class="card-content is-overlay is-clipped">
            <span class="subtitle f-15 has-text-white">Creative writing</span><br />
            <span class="title is-4 has-text-white">Resume</span>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  </section>


  


  <script>


 BulmaCarousel.attach('#carousel-category', {
    slidesToScroll: 1,
    slidesToShow: 4,
    infinite: true,
    pagination: false
  });


  </script>

app/views/pages/plans.html.erb
<section class="section">
  <div class="container">
    <p class="title is-4 m-t 50 m-b has-text-centered">
      Choose the best package for your business

    </p>
    <div class="pricing-table m-t-20 m-l-50 m-r-50">
      <% @plans.data.each do |plan| %>
      <div class="pricing-plan <%= 'is-warning' if plan.amount == 500 %>
         <%= 'is-primary is-active' if plan.amount == 1000 %>
          <%= 'is-danger' if plan.amount == 2500 %>">
        <div class="plan-header"><%= plan.nickname %></div>
        <div class="plan-price">
          <span class="plan-price-amount">
          <span class="plan-price currency">$</span><%= plan.amount / 100 %>
        </span>/month
        </div>
        <div class="plan-items">
          <div class="plan-item">
          Commission fee is <%= plan.metadata.commission %>%
          </div>
        </div>
        <div class="plan-footer">
          <%= form_with url: subscribe_url do |f| %>
          <%= f.hidden_field :plan_id, value: plan.id %>
          <%= f.submit "Choose", class: "button is-fullwidth" %>
          <% end %>
        </div>
      </div>
      <% end %>
     </div>
   </div>
 </section>

app/views/pages/search.html.erb
<%= render 'shared/categories' %>

<section class="section">
    <div class="container">

        <!-- HEADER SECTION -->
        <div class="card m-b-20">
            <div class="card-header">

    <!-- Category -->
    <div class="card-header-title">
        Gigs <% if @category %> > <%= @category.name %> <% end %>
    </div>

    <!-- Sort by Dropdown -->
    <%= form_tag '', method: :get do %>
        <%= hidden_field_tag 'category', @category ? @category.id : '' %>

        <%= hidden_field_tag 'sort', @sort %>
        <div class="field p-10">
            <div class="select">
                <%= select_tag 'sort', options_for_select(
                    [
                        ['Price Low to High', 'price asc'],
                        ['Price High to Low', 'price desc'],
                        ['Latest First', 'gigs.created_at desc'],
                        ['Oldest First', 'gigs.created_at asc']
                    ], selected: @sort
                ), onchange: "this.form.submit();" %>
            </div>
        </div>  
    <% end %>            
</div>
</div>

<div class="columns">

<!-- LEFT SIDE -->
<div class="column is-one-quarter">
<div class="columns is-multiline">

<div class="column is-full">
    <div class="card">
        <div class="card-content">

            <%= form_tag '', method: :get do %>
                <%= hidden_field_tag 'category', @category ? @category.id : '' %>
                <%= hidden_field_tag 'sort', @sort %>
                                                
                <!-- Title Search -->
                <div class="field">
                    <%= text_field_tag 'q', @q || '', class: "input", placeholder: "Search by title" %>
                </div>
                <hr/>

                <!-- Price Range -->
                <label class="label">Price Range</label>
                <div class="field has-addons">
                    <p class="control">
                        <a class="button is-static">$</a>
                    </p>
                    <p class="control">                                            
                        <%= number_field_tag 'min', @min || '', class: "input", placeholder: "Min" %>                                        
                    </p>
                </div>
                <div class="field has-addons">
                    <p class="control">
                        <a class="button is-static">$</a>
                    </p>
                    <p class="control">
                        <%= number_field_tag 'max', @max || '', class: "input", placeholder: "Max" %>
                    </p>
                </div>
                <hr/>

                <!-- Delivery Time -->
                <label class="label">Delivery Time</label>                                    
                <%= radio_button_tag 'delivery', "1", checked = "1" == @delivery %> Up to 1 days <br>
                <%= radio_button_tag 'delivery', "3", checked = "3" == @delivery %> Up to 3 days <br>
                <%= radio_button_tag 'delivery', "7", checked = "7" == @delivery %> Up to 7 days <br>
                <%= radio_button_tag 'delivery', "10", checked = "10" == @delivery %> Up to 10 days <br>
                <%= radio_button_tag 'delivery', "15", checked = "15" == @delivery %> Up to 15 days <br>
                <%= radio_button_tag 'delivery', "0", checked = "0" == @delivery %> Any
                <hr/>
                
                <!-- Buttons -->
                <div class="field m-t-20">
                    <button  class="button is-danger is-fullwidth" type="submit"> Apply</button>
                </div>

            <% end %>

            <div class="field m-t-10">
                <%= form_tag '', method: :get do %>
                    <button  class="button is-black is-outlined is-fullwidth" type="submit"> Clear All Filters</button>
                <% end %>
            </div>

        </div>
    </div>
</div>
</div>
</div>

            <!-- RIGHT SIDE -->
            <div class="column infinite-list">

                <!-- List of gigs -->
                <div class="columns is-multiline">
                    <%= render partial: 'shared/gigs', object: @gigs %>
                </div>

                <!-- Pagination -->
          <!--       <div class="card"> -->
                    <div class="card-header-title is-centered">
                     <%= paginate @gigs %>
                    </div>
                </div>
         <!--    </div> -->

        </div>
        
    </div>
</section>

app/views/shared/_alert.html.erb
 <% unless flash.empty? %>
<script>
  <% flash.each do |key, value| %>
  <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
  new Noty ({
    type: '<%= type %>',
    layout: 'topRight',
    timeout: '3000',
    theme: 'sunset',
    text: '<%= value %>' 
     }).show();
  <% end %>
  

</script>
  
<% end %>

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
  <div class="container">
    <div class="navbar">
      <% @categories.each do |item| %>
      <%= link_to "#{item.name}", search_path(category: item.id), class: "navbar-item" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_gigs.html.erb
        <% @gigs.each do |gig| %>

          <div class="column is-one-third">
            <div class="card">

              <div class="card-image">
                <%= link_to gig_path(gig) do %>
                <figure class="image is-4by3">
                  <%= image_tag gig_cover(gig) %>
                </figure>
                <% end %>
              </div>

              <div class="card-content p-t-5 p-b-5">
                <p class="subtitle is-6 m-b-5"><%= link_to gig.title.truncate(20), gig_path(gig) %></p>
                <span class="star-review"><i class="fa fa-star"></i>
                  <%= gig.average_rating %>
                  <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                </span>                                        
              </div>

              <footer class="card-footer">
                <span class="card-footer-item">
                  <%= link_to users_path(gig.user) do %>
                  <figure class="image is-32x32">
                    <%= image_tag avatar_url(gig.user), class: "is-rounded" %>
                  </figure>
                  <% end %>
          </span>
                <a class="has-text-danger is-block card-footer-item has-text-right">
                  <span class="small-title">STARTING AT</span> 
                  <strong>$<%= gig.price %></strong>
                                        
                </a>
              </footer>  

            </div>
          </div>
          <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <h1 class="title is-4 has-text-white">Cocreax</h1>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
                <%= form_tag search_path, method: :get do %>
                    <div class="field has-addons <%= 'is-hidden' if current_page?(root_path) %>">
                        <div class="control has-icons-left">
                            <span class="icon is-small is-left">
                                <i class="fa fa-search"></i>
                            </span>
                            <%= text_field_tag 'q', '', class: "input", placeholder: "Try 'logo design" %>
                        </div>
                        <div class="control">
                            <button class="button is-warning" type="submit">Search</button>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        

        <div class="navbar-end">
              <%= link_to 'Pricing', plans_path, class: "navbar-item" %>
            <%= link_to 'Post Gig', new_gig_path, class: "navbar-item" %>
        <%= link_to 'Browse Gigs', search_path, class: "navbar-item" %>

            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "Sign Up", new_user_registration_path, class: "button is-danger" %>
                        <%= link_to  "Login", new_user_session_path, class: "button is-light" %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        <figure class="image is-24x24 m-r-5">
                            <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                        </figure>
                        <%= current_user.full_name %>
                    </a>

                    <div class="navbar-dropdown">
                        <%= link_to  "Profile", edit_user_registration_path, class: "navbar-item" %>
                        <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                        <hr class="navbar-divider">
                        <%= link_to  "Log out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?(plans_path) && !current_page?(search_path) && !current_page?("/gigs/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
    <nav class="navbar has-shadow" style="z-index: 5">
        <div class="container">
            <div class="navbar">
                <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                 <%= link_to 'Calendar', calendar_path, class: "navbar-item" %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Selling</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Create New Gig', new_gig_path, class: "navbar-item" %>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Buying</a>
                    <div class="navbar-dropdown">
                       <%= link_to "Post Request", new_request_path, class: "navbar-item" %>
                        <%= link_to "Manage Request", requests_path, class: "navbar-item" %>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Buyer Requests</a>
                    <div class="navbar-dropdown">
              <%= link_to "Active Request", all_requests_path, class: "navbar-item" %>
                       <%= link_to "Offers Sent", my_offers_path, class: "navbar-item" %>                    </div>
                </div><div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Orders</a>
                      <div class="navbar-dropdown">
                    <%= link_to 'Selling Orders', selling_orders_path, class: "navbar-item" %>
                  <%= link_to 'Buying Orders', buying_orders_path, class: "navbar-item" %>
                    </div>
                </div>
                <%= link_to 'Earnings', earnings_path, class: "navbar-item" %>
                <%= link_to 'Messages', conversations_path, class: "navbar-item" %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Settings</a>
                    <div class="navbar-dropdown">
                <%= link_to 'Payment Method', settings_payment_path, class: "navbar-item" %>
              <%= link_to 'Payout Method', settings_payout_path, class: "navbar-item" %>
                    </div>
                </div>
            </div>
        </div>

    </nav>
<% end %>

<script>
$(document).ready(function() {

  // Check for click events on the navbar burger icon
  $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

  });
});
</script>